/*
# Test the Server API
*/
@host http://localhost:8080
###
# @name produce
GET /api/produce

HTTP/1.1 200  - OK
x-powered-by: Express
access-control-allow-origin: *
content-type: application/json; charset=utf-8
content-length: 4099
etag: W/"1003-ccrlqF/GjemXY4WjEE/JE+CwcgA"
date: Mon, 07 Apr 2025 15:01:17 GMT
connection: close
###
# @ref produce
# @name product
GET /api/produce/{{ produce[produce.length - 1]._id }}

HTTP/1.1 200  - OK
x-powered-by: Express
access-control-allow-origin: *
content-type: application/json; charset=utf-8
content-length: 210
etag: W/"d2-G+GMml8MkhBjrArZkHGFwaBW2NU"
date: Mon, 07 Apr 2025 15:04:50 GMT
connection: close