/*
# Test the Server API
*/
@host http://localhost:8080
###
# @name produce
GET /api/produce

HTTP/1.1 200  - OK
x-powered-by: Express
access-control-allow-origin: *
content-type: application/json; charset=utf-8
content-length: 4099
etag: W/"1003-GvRl1vwHnDyybHwmrUpRxMD06EI"
date: Mon, 07 Apr 2025 15:17:54 GMT
connection: close
###
# @ref produce
GET /api/produce/{{ produce[produce.length - 1]._id }}

HTTP/1.1 200  - OK
x-powered-by: Express
access-control-allow-origin: *
content-type: application/json; charset=utf-8
content-length: 210
etag: W/"d2-4+ou+Dd0M1GdwChJEXhpCsyhBzM"
date: Mon, 07 Apr 2025 15:18:05 GMT
connection: close
###
GET /api/produce/67f3cf586840ebb7256b140b.json